### ISSUE TITLE
Job config file fields

### ISSUE THREAD

**Issue by oskarvid** [neicnordic/Bifrost#3]
I suggest we use the yaml file format to make the job config file, it is readable and has a simple syntax.

I suggest that the config file should contain the following:  
* Job type: imputation or whatever kind of analysis that the schizophrenia project does
* Input file md5sum: "45f6esf435se4f56w", this is a mechanism to verify that the transferred files have been transferred correctly. This solves both the issue of incomplete transfers as well as files corrupted during the transfer.  

What more should it contain? Is there a better solution to the incomplete/corrupted files issue?

**Comment by radmilak** [comment]
For schizophrenia, I don't need the Input file md5sum as there is no input file. Other than the job type, there will be a few other parameters, as of now two are certain: 
1) What script to run (there will be several)
2) Where to run it - Norway, Sweden, etc.: In the first phase this would be hardcoded to Norway.
Or depending on how the Job type field would look like, number 1) could be there instead, like schizophrenia-1, schizophrenia-2 or something like that.

**Comment by oskarvid** [comment]
Added file transfer check that verified if the files that have been sent to TSD have been copied to the scratch disk already. Without this check the input files would get copied every time the cron job runs. This field is created by the [submitJob.py](https://github.com/neicnordic/Bifrost/blob/master/submitJob.py) script and edited by the [readConfig.py](https://github.com/neicnordic/Bifrost/blob/master/readConfig.py) script.

**Comment by radmilak** [comment]
There will also be some input parameters for the schizophrenia scripts, though no examples have been given, so it is yet to be decided if these would be better as parameters for the submission job or perhaps some config file (so scz would then also have a sort of input file).

**Comment by oskarvid** [comment]
Currently the config file contains the following fields:

* inputfile
* jobtype
* country
* md5sum
* encryptedmd5sum
* filecopied
* decrypting
* encryptedinput  

Some are manually defined and others automatically created, we may need to rethink how we use the config file because there is a risk that the number of flags and arguments increase far beyond what is reasonable. And right now the config file is probably used for too many things, i.e definition of input files as well as job control once the files have been submitted to TSD. Let's revisit this in time.

**Comment by oskarvid** [comment]
Currently the user must write a very long command on the command line to submit a job, some of these parameters, or most, should be manually placed in the config file instead. Since this is a quality of life improvement this will be explored once the base functionality is in place.
